const productos = [
    {
      id: 1,
      nombre: "Rabadon",
      descripcion: "Sombrero Mortífero de Rabadon es esencial para cualquier campeón con radios de poder de habilidad, tanques o carries, que desean causar un daño mágico significativo que carreará al final de la partida.",
      categoria: "AP",
      precio: 3600,
      img: "https://leagueofitems.com/images/items/256/3089.webp",
      cantidad: 1,
    },
    {
      id: 2,
      nombre: "Baculo Del Vacio",
      descripcion: "el 40% de Penetración de magia de Báculo del Vacío Báculo del Vacío se vuelve más efectivo a medida que aumenta la resistencia mágica del objetivo.",
      categoria: "AP",
      precio: 2800,
      img: "https://leagueofitems.com/images/items/256/3135.webp",
      cantidad: 1,
    },
    {
      id: 3,
      nombre: "Draktar",
      descripcion: "El daño físico adicional infligido por ACECHADOR NOCTURNO no aumenta con los modificadores de ataque.",
      categoria: "AD",
      precio: 3200,
      img: "https://leagueofitems.com/images/items/256/6691.webp",
      cantidad: 1,
    },
    {
      id: 4,
      nombre: "Fuerza De La Trinidad",
      descripcion: "El tiempo de enfriamiento comienza después de que se consume el proceso (después del ataque básico desencadenante) y los lanzamientos de habilidades consecutivos actualizan la duración del ataque mejorado.",
      categoria: "AD",
      precio: 3333,
      img: "https://leagueofitems.com/images/items/256/3078.webp",
      cantidad: 1,
    },
    {
      id: 5,
      nombre: "Aegida De Fuego Solar",
      descripcion: "IMMOLAR infligirá 20.64 − 51.6 (según el nivel) (+ 1.72% de vida adicional) como daño mágico mientras que en 6 acumulaciones, aumenta aún más a 25.8 − 64.5 (según el nivel) (+ 2.15% de vida adicional) contra súbditos y para 51.6 − 129 (según el nivel) (+4.3% de vida adicional) contra monstruos.",
      categoria: "TANQUE",
      precio: 2800,
      img: "https://leagueofitems.com/images/items/256/3068.webp",
      cantidad: 1,
    },
    {
      id: 6,
      nombre: "Guantelete De Fuego Escarchado",
      descripcion: "El objeto se llamó originalmente Frozen Fist (puño congelado), y a menudo se lo sigue llamando como tal.",
      categoria: "TANQUE",
      precio: 2800,
      img: "https://leagueofitems.com/images/items/256/6662.webp",
      cantidad: 1,
    },
  ];